# Generated by Django 5.0.4 on 2024-08-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
