# Generated by Django 5.0.4 on 2024-09-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cartitems_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
