# Generated by Django 5.0.4 on 2024-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cartitems_size_alter_cartitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
