# Generated by Django 5.0.4 on 2024-09-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cartitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
