# Generated by Django 5.0.4 on 2024-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cartitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='userid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
