# Generated by Django 5.0.4 on 2024-09-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cartitems_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='userid',
            new_name='userintId',
        ),
    ]
