# Generated by Django 5.0.4 on 2024-09-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_userid_cartitems_userintid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='countInStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
