# Generated by Django 5.0.4 on 2024-09-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_order_shippinprice_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cartItems',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
