# Generated by Django 5.0.4 on 2024-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_shippingaddress_shippingprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
