# Generated by Django 5.0.4 on 2024-09-11 06:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Paidamount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='paidAt',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpayorder_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Signature'),
        ),
    ]
