# Generated by Django 5.0.4 on 2024-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_transaction_cartorder_id_transaction_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Cartorder_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Cart_order_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Order ID'),
        ),
    ]
