# Generated by Django 5.0.4 on 2024-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_transaction_cart_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Razorpay_Payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Razorpay_signature_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
